// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCaBo2w_NjaatThS5-7UaYV6weNqQfINQ',
    appId: '1:1061651412992:web:c5c492cf8da040290380e5',
    messagingSenderId: '1061651412992',
    projectId: 'quizieee',
    authDomain: 'quizieee.firebaseapp.com',
    storageBucket: 'quizieee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR82IgeCeka3ZYbb4y6_cXklc-I1aBd18',
    appId: '1:1061651412992:android:8ee2ae785c9212dd0380e5',
    messagingSenderId: '1061651412992',
    projectId: 'quizieee',
    storageBucket: 'quizieee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlDrwHgltqkkGqhmm6WQXyhwtN9H8kIMI',
    appId: '1:1061651412992:ios:bbe838e9ddff761f0380e5',
    messagingSenderId: '1061651412992',
    projectId: 'quizieee',
    storageBucket: 'quizieee.appspot.com',
    iosBundleId: 'com.dcaayush.codes.quizieee',
  );
}
